
log:
	tail -f /var/log/dome.log
err: 
	tail -f /var/log/dome.err
pid:
	tail -f /var/log/dome.pid
restart:
	sudo service dome restart
r: restart

disable:
	sudo update-rc.d dome disable
enable:
	sudo update-rc.d dome enable
